version: '3.3'

# Setup network
networks:
  default:
    name: fedn_default

services:
  # Base services
  minio:
    image: minio/minio:latest
    # hostname: minio
    environment:
      # - GET_HOSTS_FROM=dns
      - MINIO_HOST=localhost
      - MINIO_PORT=9000
      - MINIO_ROOT_USER=fedn_admin
      - MINIO_ROOT_PASSWORD=password
    command: server /data --console-address localhost:9001
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:9000/minio/health/live"
        ]
      interval: 30s
      timeout: 20s
      retries: 3
    # ports:
    #   - 9000:9000
    #   - 9001:9001
    network_mode: "host" # TODO: configure network in enclave to avoid this

  mongo:
    image: mongo:5.0.2
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=fedn_admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    # ports:
    #   - 6534:6534
    command: mongod --port 6534
    network_mode: "host" # TODO: configure network in enclave to avoid this

  mongo-express:
    image: mongo-express:latest
    restart: always
    depends_on:
      - "mongo"
    environment:
      - ME_CONFIG_MONGODB_SERVER=localhost
      - ME_CONFIG_MONGODB_PORT=6534
      - ME_CONFIG_MONGODB_ADMINUSERNAME=fedn_admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_BASICAUTH_USERNAME=fedn_admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password
    # ports:
    #   - 8081:8081
    network_mode: "host" # TODO: configure network in enclave to avoid this

  # Reducer
  reducer:
    image: ghcr.io/scaleoutsystems/tee-gc/fedn
    environment:
      # - GET_HOSTS_FROM=dns
      - USER=test
      - PROJECT=project
    command: reducer
    privileged: true # to access SGX devices
    # ports:
    #   - 8090:8090
    network_mode: "host" # TODO: configure network in enclave to avoid this

  # Combiner
  combiner:
    image: ghcr.io/scaleoutsystems/tee-gc/fedn
    environment:
      # - GET_HOSTS_FROM=dns
      - PYTHONUNBUFFERED=0
    command: combiner
    privileged: true # to access SGX devices
    # ports:
    #   - 12080:12080
    network_mode: "host" # TODO: configure network in enclave to avoid this

  # Client
  client:
    build: .
    environment:
      # - GET_HOSTS_FROM=dns
      - TMPDIR=/tmp
    command: run client -in config/settings-client.yaml
    network_mode: "host" # TODO: configure network in enclave to avoid this
    volumes:
      - ${HOST_GIT_DIR:-./}:/app/data
      - ${HOST_GIT_DIR:-./}/config/settings-client.yaml:/app/config/settings-client.yaml